### ISSUE TITLE
grunt-html2js task never ends because of typo in .html file

### ISSUE THREAD

**Issue by Wanderduene** [rquadling/grunt-html2js#63] opened 2015-02-18 15:17 UTC
Hi,

we had the problem in our project that the build never ends because the task "grunt-html2-js" seems to "hang". I could trace back the problem to an HTML file where the developer made a mistake by using one double quote to much. I set up an example project to reproduce the issue.
This is my package.json:

``` javascript
{
  "name": "testApp",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "XXX",
  "license": "ISC",
  "dependencies": {
    "grunt": "^0.4.5",
    "grunt-cli": "^0.1.13",
    "grunt-html2js": "^0.3.0",
    "grunt-init": "^0.3.2"
  }
}
```

and my gruntfile.js:

``` javascript
'use strict';

module.exports = function (grunt) {

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        html2js: {
            options: {
                module: 'testApp-templates',
                base: 'app',
                htmlmin: {
                    collapseBooleanAttributes: true,
                    collapseWhitespace: true,
                    removeAttributeQuotes: true,
                    removeComments: true,
                    removeEmptyAttributes: true,
                    removeRedundantAttributes: true,
                    removeScriptTypeAttributes: true,
                    removeStyleLinkTypeAttributes: true
                }
            },
            main: {
                src: ['app/components/**/*.html'],
                dest: 'dist/templates.js'

            }
        }
    });

    grunt.loadNpmTasks('grunt-html2js');

    grunt.registerTask('default', ['html2js']);
};
```

Then I added in the folder app/components/html/testComp.html the buggy HTML code (the unnecessary double quote is at the end of the first line):

``` html
<div class="col-sm-4" as-sortable="dragControlListeners" ng-model="itemsZiele" style="min-height:250px; border-right-style: solid;"">
</div>
```

When I now start grunt I have the same problem, that the task never ends. 

My expactation would be that the task should crash with an parser error or give a warning.

**Comment by RBLU** [comment] 2015-03-17 06:30
just had the same symptom - hanging, never ending task. Reason was a wrong , (comma) character at a place where it does not belong to in the html:

      <div class="col-sm-3",
      </div>

**Comment by sentient** [comment] 2015-04-24 15:14
Same issue here. I have a watch task to do continuous build and that was suddenly hanging. 
Is there anything that can be done that html2js fails or errors out on invalid html. Or do we need to setup a pre-task to validate that the html is valid before this tasks runs?

**Comment by johnSowingo** [comment] 2015-08-25 14:23
+1

**Comment by bryanerayner** [comment] 2015-10-01 21:08
I'm also getting this problem. Not sure the cause.

**Comment by yoav-zibin** [comment] 2015-11-28 22:27
Yes, I got the same problem. It just hangs...

**Comment by marklieberman** [comment] 2016-02-22 16:21
Same problem due to this typo:
```
<button data-popover-template-"views/popover.html">
```
Note the attribute has a `-` instead of a `=`.

**Comment by RBLU** [comment] 2016-02-23 07:12
it probably hangs inside the minifier, which is not part of this project. It is a dependency to https://github.com/kangax/html-minifier. Currently version ~0.6.0 is used, but html-minifier is maintained pretty actively, the current version is 1.2.0. Maybe try whether updading the dependency in package.json to 1.2.0 fixes this issue.

**Comment by davidparsson** [comment] 2016-02-25 16:01
I've seen this too a long time ago, but I'm actually unable to reproduce this now with any of your minimal examples. Adding each of your examples and building them (alone) works fine for me.

**Comment by davidparsson** [comment] 2016-02-26 00:38
I'd like to add that I only tried to reproduce this by creating a fork and adding a failing test case.

**Comment by rquadling** [comment] 2017-05-19 13:54
Closing due to being over 1 year old.

**Closed by rquadling** 2017-05-19 13:54 UTC
